# Generated by Django 3.0.5 on 2020-04-11 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200411_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_contents',
            new_name='blog_content',
        ),
    ]
