# Generated by Django 3.0.5 on 2020-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200411_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_content',
            name='status',
        ),
        migrations.AddField(
            model_name='blog_article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
