# Generated by Django 3.0.5 on 2020-04-14 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20200412_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_article',
            options={},
        ),
        migrations.AddField(
            model_name='blog_article',
            name='author',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='blog_article',
            name='content',
            field=models.TextField(null=2),
            preserve_default=2,
        ),
        migrations.AddField(
            model_name='blog_article',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog_article',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='blog_content',
        ),
    ]
