# Generated by Django 3.0.5 on 2020-04-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200414_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_article',
            name='author',
        ),
    ]
