# Generated by Django 3.0.5 on 2020-04-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='blog_article',
            name='author',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.author'),
            preserve_default=1,
        ),
    ]
